resources:
  - ../../../base
configMapGenerator:
  - name:  env-sampleapp
    behavior: merge
    literals:
    - NETDOCUMENTS_REGION=dev
    - KEY_VAULT_NAME=nd-uscp-sampleapp-kv
images:
  - name: sampleapp
    newName: nduscpcr.azurecr.io/modsnd/sampleapp
    newTag: junk
patches:
  - path: ./hpa.yaml
  - target:
      kind: Ingress
      name: sampleapp
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: sampleapp-qa.netdocuments.com