---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sampleapp-cpu-autoscaler
  labels:
    app.kubernetes.io/name: sampleapp
    app.kubernetes.io/instance: sampleapp
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1200
    scaleUp:
      stabilizationWindowSeconds: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sampleapp
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 250m